- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "DevSecOps with AWS" # string
    DURATION: "140" # int/number
    IS_LIVE: true # bool
    DETAILS: # map/directory
      MONTHS: 4
      TRAINER: "Sivakumar Reddy"
    TOPICS: # list -/[]
    - Linux
    - Shell
    - Ansible
  tasks:
  - name: print variables
    Ansible.builten.debug:
      msg: |
        PROGRAM: {{ PROGRAM }}
        DURATION:  {{ DURATION }}
        IS_LIVE:  {{ IS_LIVE }}
        DETAILS:  {{ DETAILS }}
        TOPICS:   {{ TOPICS }}
        