- name: Install Packages
  hosts: local
  connection: local
  become: Yes
  tasks:
  - name: Install package
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip