- name: "Chand"
  dob: "1990-01-01"
  mobileNumber: 1234567890
  address:
  - flatNumber: 207
    street: "santosh nagar"
    city: "hyderabad"
    type: "current"

  - flatNumber: 207
    street: "santosh nagar"
    city: "hyderabad"
    type: "perm"

- name: "Gopi"
  dob: "1990-01-01"
  mobileNumber: 1234567890
  address:
  - flatNumber: 207
    street: "santosh nagar"
    city: "hyderabad"
    type: "current"

  - flatNumber: 207
    street: "santosh nagar"
    city: "hyderabad"
    type: "perm"